# Generated by Django 5.2.17 on 2026-09-20 05:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('cupos_totales', models.PositiveSmallIntegerField()),
                ('cupos_ocupados', models.PositiveSmallIntegerField(default=0)),
                ('estado', models.CharField(choices=[('abierta', 'Abierta'), ('cubierta', 'Cubierta'), ('cancelada', 'Cancelada')], default='abierta', max_length=20)),
                ('es_activo', models.BooleanField(default=True)),
                ('desactivado_en', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('desactivado_por', models.ForeignKey(blank=True, db_column='desactivado_por_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('proyecto', models.ForeignKey(db_column='proyecto_id', on_delete=django.db.models.deletion.CASCADE, related_name='vacantes', to='projects.proyecto')),
            ],
            options={
                'db_table': 'vacantes',
            },
        ),
    ]
