# Generated by Django 5.2.17 on 2026-09-20 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_vacante'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProyectoMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('logo', 'Logo'), ('prototipo', 'Prototipo')], max_length=20)),
                ('archivo_url', models.TextField()),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('es_activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('proyecto', models.ForeignKey(db_column='proyecto_id', on_delete=django.db.models.deletion.CASCADE, related_name='media', to='projects.proyecto')),
            ],
            options={
                'db_table': 'proyecto_media',
            },
        ),
    ]
