# Generated by Django 5.2.17 on 2026-09-20 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('projects', '0003_proyectomedia'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacanteHabilidadRequerida',
            fields=[
                ('pk', models.CompositePrimaryKey('vacante_id', 'habilidad_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('habilidad', models.ForeignKey(db_column='habilidad_id', on_delete=django.db.models.deletion.RESTRICT, to='accounts.habilidad')),
                ('vacante', models.ForeignKey(db_column='vacante_id', on_delete=django.db.models.deletion.CASCADE, to='projects.vacante')),
            ],
            options={
                'db_table': 'vacante_habilidades_requeridas',
            },
        ),
        migrations.CreateModel(
            name='VacanteTecnologiaRequerida',
            fields=[
                ('pk', models.CompositePrimaryKey('vacante_id', 'tecnologia_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('tecnologia', models.ForeignKey(db_column='tecnologia_id', on_delete=django.db.models.deletion.RESTRICT, to='accounts.tecnologia')),
                ('vacante', models.ForeignKey(db_column='vacante_id', on_delete=django.db.models.deletion.CASCADE, to='projects.vacante')),
            ],
            options={
                'db_table': 'vacante_tecnologias_requeridas',
            },
        ),
    ]
