# Generated by Django 5.2.17 on 2026-09-19 17:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(db_column='password_hash', max_length=128)),
                ('last_login', models.DateTimeField(blank=True, db_column='ultimo_login', null=True)),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('es_admin', models.BooleanField(default=False)),
                ('es_activo', models.BooleanField(default=True)),
                ('esta_bloqueado', models.BooleanField(default=False)),
                ('motivo_bloqueo', models.TextField(blank=True, null=True)),
                ('bloqueado_en', models.DateTimeField(blank=True, null=True)),
                ('desactivado_en', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('bloqueado_por', models.ForeignKey(blank=True, db_column='bloqueado_por_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_bloqueados', to=settings.AUTH_USER_MODEL)),
                ('desactivado_por', models.ForeignKey(blank=True, db_column='desactivado_por_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_desactivados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='Habilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('es_activo', models.BooleanField(default=True)),
                ('desactivado_en', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.CharField(blank=True, max_length=50, null=True)),
                ('desactivado_por', models.ForeignKey(blank=True, db_column='desactivado_por_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'habilidades',
            },
        ),
        migrations.CreateModel(
            name='Interes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('es_activo', models.BooleanField(default=True)),
                ('desactivado_en', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('desactivado_por', models.ForeignKey(blank=True, db_column='desactivado_por_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'intereses',
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('principiante', 'Principiante'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado')], default='principiante', max_length=20)),
                ('experiencia_anios', models.PositiveSmallIntegerField(default=0)),
                ('disponibilidad_horas_semana', models.PositiveSmallIntegerField(default=10)),
                ('bio', models.TextField(blank=True, null=True)),
                ('github_username', models.CharField(blank=True, max_length=100, null=True)),
                ('avatar_url', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'perfiles',
            },
        ),
        migrations.CreateModel(
            name='Tecnologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('es_activo', models.BooleanField(default=True)),
                ('desactivado_en', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.CharField(blank=True, max_length=50, null=True)),
                ('desactivado_por', models.ForeignKey(blank=True, db_column='desactivado_por_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tecnologias',
            },
        ),
        migrations.CreateModel(
            name='UsuarioHabilidad',
            fields=[
                ('pk', models.CompositePrimaryKey('usuario_id', 'habilidad_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('habilidad', models.ForeignKey(db_column='habilidad_id', on_delete=django.db.models.deletion.RESTRICT, to='accounts.habilidad')),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'usuarios_habilidades',
            },
        ),
        migrations.CreateModel(
            name='UsuarioInteres',
            fields=[
                ('pk', models.CompositePrimaryKey('usuario_id', 'interes_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('interes', models.ForeignKey(db_column='interes_id', on_delete=django.db.models.deletion.RESTRICT, to='accounts.interes')),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'usuarios_intereses',
            },
        ),
        migrations.CreateModel(
            name='UsuarioTecnologia',
            fields=[
                ('pk', models.CompositePrimaryKey('usuario_id', 'tecnologia_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('tecnologia', models.ForeignKey(db_column='tecnologia_id', on_delete=django.db.models.deletion.RESTRICT, to='accounts.tecnologia')),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'usuarios_tecnologias',
            },
        ),
    ]
