# Generated by Django 5.2.17 on 2026-09-20 22:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0004_vacantehabilidadrequerida_vacantetecnologiarequerida"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Reporte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_objetivo",
                    models.CharField(
                        choices=[
                            ("proyecto", "Proyecto"),
                            ("perfil", "Perfil"),
                            ("conducta", "Conducta"),
                        ],
                        max_length=20,
                    ),
                ),
                ("motivo", models.CharField(max_length=150)),
                ("descripcion", models.TextField(blank=True, null=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("en_revision", "En revisión"),
                            ("resuelto", "Resuelto"),
                            ("descartado", "Descartado"),
                        ],
                        default="pendiente",
                        max_length=20,
                    ),
                ),
                ("decision", models.TextField(blank=True, null=True)),
                ("resuelto_en", models.DateTimeField(blank=True, null=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "proyecto_reportado",
                    models.ForeignKey(
                        blank=True,
                        db_column="proyecto_reportado_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reportes",
                        to="projects.proyecto",
                    ),
                ),
                (
                    "reportante",
                    models.ForeignKey(
                        blank=True,
                        db_column="reportante_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reportes_hechos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resuelto_por",
                    models.ForeignKey(
                        blank=True,
                        db_column="resuelto_por_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "usuario_reportado",
                    models.ForeignKey(
                        blank=True,
                        db_column="usuario_reportado_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reportes_recibidos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "reportes",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("proyecto_reportado__isnull", True),
                                ("tipo_objetivo__in", ["perfil", "conducta"]),
                                ("usuario_reportado__isnull", False),
                            ),
                            models.Q(
                                ("proyecto_reportado__isnull", False),
                                ("tipo_objetivo", "proyecto"),
                                ("usuario_reportado__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="chk_objetivo_reporte",
                    )
                ],
            },
        ),
    ]
