# Generated by Django 5.2.17 on 2026-09-20 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ConfiguracionPesosMatching",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                (
                    "peso_habilidades",
                    models.DecimalField(decimal_places=3, max_digits=4),
                ),
                ("peso_nivel", models.DecimalField(decimal_places=3, max_digits=4)),
                (
                    "peso_tecnologias",
                    models.DecimalField(decimal_places=3, max_digits=4),
                ),
                (
                    "peso_experiencia",
                    models.DecimalField(decimal_places=3, max_digits=4),
                ),
                (
                    "peso_disponibilidad",
                    models.DecimalField(decimal_places=3, max_digits=4),
                ),
                ("vigente_desde", models.DateTimeField(auto_now_add=True)),
                ("vigente_hasta", models.DateTimeField(blank=True, null=True)),
                ("es_activo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Configuración de pesos de matching",
                "verbose_name_plural": "Configuraciones de pesos de matching",
                "db_table": "configuracion_pesos_matching",
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("es_activo", True)),
                        fields=("es_activo",),
                        name="ux_un_solo_peso_activo",
                    )
                ],
            },
        ),
    ]
