# Generated by Django 5.2.17 on 2026-09-20 22:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("matching", "0001_initial"),
        ("projects", "0004_vacantehabilidadrequerida_vacantetecnologiarequerida"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Postulacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("preseleccionada", "Preseleccionada"),
                            ("aceptada", "Aceptada"),
                            ("rechazada", "Rechazada"),
                            ("retirada", "Retirada"),
                        ],
                        default="pendiente",
                        max_length=20,
                    ),
                ),
                ("match_score", models.DecimalField(decimal_places=2, max_digits=5)),
                ("match_factores", models.JSONField()),
                ("motivo_decision", models.TextField(blank=True, null=True)),
                ("postulado_en", models.DateTimeField(auto_now_add=True)),
                ("decidido_en", models.DateTimeField(blank=True, null=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "decidido_por",
                    models.ForeignKey(
                        blank=True,
                        db_column="decidido_por_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pesos_usados",
                    models.ForeignKey(
                        blank=True,
                        db_column="pesos_usados_id",
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to="matching.configuracionpesosmatching",
                    ),
                ),
                (
                    "postulante",
                    models.ForeignKey(
                        db_column="postulante_id",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="postulaciones",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vacante",
                    models.ForeignKey(
                        db_column="vacante_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="postulaciones",
                        to="projects.vacante",
                    ),
                ),
            ],
            options={
                "db_table": "postulaciones",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("match_score__gte", 0), ("match_score__lte", 100)
                        ),
                        name="chk_match_score_rango",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("estado__in", ["pendiente", "preseleccionada"])
                        ),
                        fields=("vacante", "postulante"),
                        name="ux_postulacion_activa_unica",
                    ),
                ],
            },
        ),
    ]
