# Generated by Django 5.2.17 on 2026-09-20 22:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0004_vacantehabilidadrequerida_vacantetecnologiarequerida"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Invitacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("aceptada", "Aceptada"),
                            ("rechazada", "Rechazada"),
                            ("ignorada", "Ignorada"),
                        ],
                        default="pendiente",
                        max_length=20,
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("respondido_en", models.DateTimeField(blank=True, null=True)),
                (
                    "invitado_por",
                    models.ForeignKey(
                        db_column="invitado_por_id",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="invitaciones_enviadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "usuario_invitado",
                    models.ForeignKey(
                        db_column="usuario_invitado_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitaciones_recibidas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vacante",
                    models.ForeignKey(
                        db_column="vacante_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitaciones",
                        to="projects.vacante",
                    ),
                ),
            ],
            options={
                "db_table": "invitaciones",
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("estado", "pendiente")),
                        fields=("vacante", "usuario_invitado"),
                        name="ux_invitacion_pendiente_unica",
                    )
                ],
            },
        ),
    ]
