# Generated by Django 5.2.17 on 2026-09-20 22:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0001_initial"),
        ("projects", "0004_vacantehabilidadrequerida_vacantetecnologiarequerida"),
        ("teams", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EquipoMembresia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[("activo", "Activo"), ("retirado", "Retirado")],
                        default="activo",
                        max_length=20,
                    ),
                ),
                ("ingreso_en", models.DateTimeField(auto_now_add=True)),
                ("retiro_en", models.DateTimeField(blank=True, null=True)),
                (
                    "invitacion",
                    models.ForeignKey(
                        blank=True,
                        db_column="invitacion_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="membresias",
                        to="teams.invitacion",
                    ),
                ),
                (
                    "postulacion",
                    models.ForeignKey(
                        blank=True,
                        db_column="postulacion_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="membresias",
                        to="applications.postulacion",
                    ),
                ),
                (
                    "proyecto",
                    models.ForeignKey(
                        db_column="proyecto_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="membresias",
                        to="projects.proyecto",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        db_column="usuario_id",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="membresias",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vacante",
                    models.ForeignKey(
                        db_column="vacante_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="membresias",
                        to="projects.vacante",
                    ),
                ),
            ],
            options={
                "db_table": "equipos_membresias",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("invitacion__isnull", True),
                                ("postulacion__isnull", False),
                            ),
                            models.Q(
                                ("invitacion__isnull", False),
                                ("postulacion__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="chk_origen_membresia",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("estado", "activo")),
                        fields=("vacante", "usuario"),
                        name="ux_membresia_activa_unica",
                    ),
                ],
            },
        ),
    ]
