# Generated by Django 5.2.17 on 2026-09-20 22:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0004_vacantehabilidadrequerida_vacantetecnologiarequerida"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Resena",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("calificacion", models.SmallIntegerField()),
                ("comentario", models.TextField(blank=True, null=True)),
                ("es_activo", models.BooleanField(default=True)),
                ("desactivado_en", models.DateTimeField(blank=True, null=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "autor",
                    models.ForeignKey(
                        db_column="autor_id",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="resenas_escritas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "desactivado_por",
                    models.ForeignKey(
                        blank=True,
                        db_column="desactivado_por_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "destinatario",
                    models.ForeignKey(
                        db_column="destinatario_id",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="resenas_recibidas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "proyecto",
                    models.ForeignKey(
                        db_column="proyecto_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resenas",
                        to="projects.proyecto",
                    ),
                ),
            ],
            options={
                "db_table": "resenas",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("calificacion__gte", 1), ("calificacion__lte", 5)
                        ),
                        name="chk_calificacion_rango",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("autor", models.F("destinatario")), _negated=True
                        ),
                        name="chk_no_autoresena",
                    ),
                    models.UniqueConstraint(
                        fields=("proyecto", "autor", "destinatario"),
                        name="ux_resena_unica",
                    ),
                ],
            },
        ),
    ]
